import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * File size, as a rule that FAILS.
 *
 * `frontdesk-board.tsx` (2,582 lines) and the invoice screen (2,274) have been named in writing
 * in the assessment for months and have kept growing in every report. A two-thousand-line file
 * does not get reviewed: it gets skimmed. And they are exactly the two places money flows through.
 *
 * `CEILING` is for what is born today. `DEBT` holds the ones that were already big, with their
 * current size as the maximum: that list may only SHRINK. When a component is split, lower its
 * number or delete the line. Adding a new entry is admitting debt — it gets discussed, not slipped
 * into a passing commit.
 *
 * Lint BLOCKS in CI (`.github/workflows/ci.yml`), so this is not advice.
 */
const CEILING = 600;

const DEBT = {
  "components/frontdesk/frontdesk-board.tsx": 2582,
  "app/(app)/billing/invoices/[id]/page.tsx": 2274,
  "components/inventario/productos-admin.tsx": 1048,
  "components/configuracion/menu-editor.tsx": 700,
  "components/servicios/servicios-admin.tsx": 686,
  "components/agenda/dia-view.tsx": 644,
  "components/auditoria/auditoria-log.tsx": 643,
  "components/admin/rbac-settings.tsx": 615,
  "components/clientes/paciente-form-sheet.tsx": 609,
};

const maxLines = (max) => ({
  "max-lines": ["error", { max, skipBlankLines: false, skipComments: false }],
});

/**
 * Next routes are full of `(groups)` and `[params]`, which in a glob are NOT literal text: `[id]`
 * is a character class and `(app)` a group. Unescaped, the ceiling for
 * `app/(app)/billing/invoices/[id]/page.tsx` matched nothing and the 2,274-line file was measured
 * against the general maximum instead — a ceiling that exists but does not apply is the worst of
 * both worlds, because it looks like it is in place.
 */
const asGlob = (route) => route.replace(/[()[\]]/g, (c) => `\\${c}`);

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run gen:api` from the backend's OpenAPI: ~19,700 lines nobody writes
    // by hand and which are regenerated wholesale.
    "lib/api/schema.d.ts",
  ]),
  // Order matters: in flat config the LAST matching block wins. General ceiling first, then the
  // exemptions, and finally the debt with its own per-file ceiling.
  {
    files: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}", "hooks/**/*.{ts,tsx}"],
    rules: maxLines(CEILING),
  },
  {
    // shadcn primitives vendored into the repo and regenerated by its CLI: their size is not our
    // decision, so measuring it would only produce noise.
    files: ["components/ui/**"],
    rules: { "max-lines": "off" },
  },
  ...Object.entries(DEBT).map(([file, max]) => ({
    files: [asGlob(file)],
    rules: maxLines(max),
  })),
]);

export default eslintConfig;
